PayMe.Webapp/Controllers/PayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PayMe.Entity;
using PayMe.Services;
using PayMe.Webapp.Models;
using RotativaCore;

namespace PayMe.Webapp.Controllers
{
    public class PayController : Controller
    {
        private readonly IPayService _pay;
        private readonly IEmployeeService _employee;
        private readonly IDeductionService _deduction;
      
        private decimal overtimeHours;
        private decimal overtimeEarnings;
        private decimal contractedEarnings;
        private decimal unionFee;
        private decimal totalEarnings;
        private decimal totalDeduction;
        private decimal studentLoanRepay;
        private decimal taxCount;
        private decimal kiwiSave;

        public PayController(IPayService pay, IEmployeeService employee, IDeductionService deduction)
        {
            _pay = pay;
            _employee = employee;
            _deduction = deduction;
        }
        public IActionResult Index()
        {
            var payRecord = _pay.GetAll().Select(pay => new PayIndexViewModel()
            {
                Id = pay.Id,
                EmployeeId = pay.EmployeeId,
                Employee = pay.Employee,
                PayDate = pay.PayDate,
                TotalDeduction = pay.TotalDeduction,
                FullName = pay.FullName,
                NetPayment = pay.NetPayment,
                PayMonth = pay.PayMonth,
                Year = _pay.GetTaxYearById(pay.TaxYearId).YearOfTax,
                TaxYearId = pay.TaxYearId,
                TotalEarnings = pay.TotalEarnings

            });
            return View(payRecord);
        }
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.employees = _employee.EmployeeList();
            ViewBag.taxYears = _pay.GetAllTaxYears();
            
            var model = new PayCreateViewModel();
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken] // prevents cross site request forgery attack

        public async Task<IActionResult> Create(PayCreateViewModel model)
        {
            if (ModelState.IsValid == false)
            {
                ViewBag.employees = _employee.EmployeeList();
                ViewBag.taxYears = _pay.GetAllTaxYears();
                return View();
            }
            var payRecord = new PaymentRecord()
            {
                Id = model.Id,
                EmployeeId = model.EmployeeId,
                Employee = model.Employee,
                PayDate = model.PayDate,
                ContractedHours = model.ContractedHours,
                HourlyRate = model.HourlyRate,
                HoursWorked = model.HoursWorked,
                PayMonth = model.PayMonth,
                TaxYearId = model.TaxYearId,
                TaxCode = model.TaxCode,

                FullName = _employee.GetEmployeeById(model.EmployeeId).FullName,
                Nino = _employee.GetEmployeeById(model.EmployeeId).PersonalInfoEmployee.NSN,

                OverTimeHours = overtimeHours = _pay.OverTimeHours(model.HoursWorked, model.ContractedHours),
                ContractedEarnings = contractedEarnings = _pay.ContractualEarnings(model.HoursWorked, model.ContractedHours, model.HourlyRate),
                OverTimeEarnings = overtimeEarnings = _pay.OverTimeEarnings(_pay.OverTimeRate(model.HourlyRate), overtimeHours),
                TotalEarnings = totalEarnings = _pay.TotalEarnings(overtimeEarnings, contractedEarnings),
                StudentLoanRepay = studentLoanRepay = _deduction.StudentLoanRepay(model.EmployeeId, totalEarnings),
                UnionFee = unionFee = _deduction.UnionFees(model.EmployeeId),
                KiwiSaver = kiwiSave = _deduction.KiwiSaverDeduction(totalEarnings),
                Tax = taxCount = _deduction.TaxAmount(totalEarnings),
                TotalDeduction = totalDeduction = _pay.TotalDeductions(taxCount, kiwiSave, studentLoanRepay, unionFee),
                NetPayment = _pay.NetPay(totalEarnings, totalDeduction)
                               

            };
            await _pay.CreateAsync(payRecord);
            return RedirectToAction(nameof(Index));


        }

        public IActionResult Detail(int id)
        {
            var paymentRecord = _pay.GetById(id);
            if (paymentRecord == null)
            {
                return NotFound();
            }
            var model = new PayDetailViewModel()
            {
                Id = paymentRecord.Id,
                PayDate = paymentRecord.PayDate,
                FullName = paymentRecord.FullName,
                UnionFee = paymentRecord.UnionFee,
                ContractedEarnings = paymentRecord.ContractedEarnings,
                TotalDeduction = paymentRecord.TotalDeduction,
                ContractedHours = paymentRecord.ContractedHours,
                Employee = paymentRecord.Employee,
                EmployeeId = paymentRecord.EmployeeId,
                HourlyRate = paymentRecord.HourlyRate,
                HoursWorked = paymentRecord.HoursWorked,
                KiwiSaver = paymentRecord.KiwiSaver,
                NetPayment = paymentRecord.NetPayment,
                StudentLoanRepay = paymentRecord.StudentLoanRepay,
                Nino = paymentRecord.Nino,
                OverTimeEarnings = paymentRecord.OverTimeEarnings,
                OverTimeHours = paymentRecord.OverTimeHours,
                OverTimeRate = _pay.OverTimeRate(paymentRecord.HourlyRate),
                PayMonth=paymentRecord.PayMonth,
                Tax=paymentRecord.Tax,
                Year=_pay.GetTaxYearById(paymentRecord.TaxYearId).YearOfTax,
                TaxYear = paymentRecord.TaxYear,
                TaxCode=paymentRecord.TaxCode,
                TaxYearId=paymentRecord.TaxYearId,
                TotalEarnings=paymentRecord.TotalEarnings
            };
            return View(model);
        }
        [HttpGet]
        public IActionResult PaySlip(int id)
        {
            var paymentRecord = _pay.GetById(id);
            if (paymentRecord == null)
            {
                return NotFound();
            }
            var model = new PayDetailViewModel()
            {
                Id = paymentRecord.Id,
                PayDate = paymentRecord.PayDate,
                FullName = paymentRecord.FullName,
                UnionFee = paymentRecord.UnionFee,
                ContractedEarnings = paymentRecord.ContractedEarnings,
                TotalDeduction = paymentRecord.TotalDeduction,
                ContractedHours = paymentRecord.ContractedHours,
                Employee = paymentRecord.Employee,
                EmployeeId = paymentRecord.EmployeeId,
                HourlyRate = paymentRecord.HourlyRate,
                HoursWorked = paymentRecord.HoursWorked,
                KiwiSaver = paymentRecord.KiwiSaver,
                NetPayment = paymentRecord.NetPayment,
                StudentLoanRepay = paymentRecord.StudentLoanRepay,
                Nino = paymentRecord.Nino,
                OverTimeEarnings = paymentRecord.OverTimeEarnings,
                OverTimeHours = paymentRecord.OverTimeHours,
                OverTimeRate = _pay.OverTimeRate(paymentRecord.HourlyRate),
                PayMonth = paymentRecord.PayMonth,
                Tax = paymentRecord.Tax,
                Year = _pay.GetTaxYearById(paymentRecord.TaxYearId).YearOfTax,
                TaxYear = paymentRecord.TaxYear,
                TaxCode = paymentRecord.TaxCode,
                TaxYearId = paymentRecord.TaxYearId,
                TotalEarnings = paymentRecord.TotalEarnings
            };
            return View(model);
        }

        public IActionResult GeneratePDF(int id)
        {
            var payslip = new ActionAsPdf("Payslip", new { id = id })
            {
                FileName = "payslip.pdf",

            };
            return payslip;
        }
    }
}

PayMe.Webapp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PayMe.Webapp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" />

</head>
<body>

    <div class="container-scroller">
        <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
                <a class="navbar-brand brand-logo"><img src="~/images/Paycompute2.gif" alt="logo" /></a>
            </div>
            <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
                <partial name="_LoginPartial" />
            </div>
        </nav>
        <div class="container-fluid page-body-wrapper">
            <nav class="sidebar sidebar-offcanvas" id="sidebar">
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="collapse" href="#Employee" aria-expanded="false" aria-controls="ui-basic">
                            <i class="fas fa-users fa-lg text-primary" style="margin-right:0.7em"></i>
                            <span class="menu-title">Employee</span>
                            <i class="menu-arrow text-primary"></i>
                        </a>
                        <div class="collapse" id="Employee">
                            <ul class="nav flex-column sub-menu">
                                <li class="nav-item"><a class="nav-link" asp-controller="Employee" asp-action="Create">Create Employee</a></li>
                                <li class="nav-item"><a class="nav-link" asp-controller="Employee" asp-action="Index">View Employees</a></li>
                            </ul>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="collapse" href="#Payroll" aria-expanded="false" aria-controls="ui-basic">
                            <i class="fas fa-pound-sign fa-lg text-primary" style="margin-right:0.7em"></i>
                            <span class="menu-title">Payroll</span>
                            <i class="menu-arrow text-primary"></i>
                        </a>
                        <div class="collapse" id="Payroll">
                            <ul class="nav flex-column sub-menu">
                                <li class="nav-item"><a class="nav-link" asp-controller="Pay" asp-action="Create">New Pay</a></li>
                                <li class="nav-item"><a class="nav-link" asp-controller="Pay" asp-action="Index">Pay Records</a></li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </nav>

            <div class="main-panel">
                <div class="content-wrapper">
                    @RenderBody()
                </div>
                <footer class="footer">
                    <p>&copy: @DateTime.UtcNow.Year - PayMe - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></p>
                </footer>
            </div>
        </div>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

PayMe.Webapp/Views/Shared/_basicEmpInfoPartial.cshtml
@model EmployeeCreateViewModel
   
                <form method="post" enctype="multipart/form-data" asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-row">
                        <div class="form-group col-md-2">
                            <label asp-for="EmpId"></label>
                        </div>
                        <div class="form-group col-md-3">
                            <input asp-for="EmpId" class="form-control" placeholder="EMP000" />
                            <span asp-validation-for="EmpId" class="text-danger"></span>
                        </div>
                        <div class="col-md-2"></div>
                      
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-2">
                            <label asp-for="FirstName"></label>
                        </div>
                        <div class="form-group col-md-3">
                            <input asp-for="FirstName" class="form-control" placeholder="Enter First Name.." />
                            <span asp-validation-for="FirstName" class="text-danger"></span>
                        </div>
                        <div class="col-md-2">
                            <input asp-for="MiddleName" class="form-control" placeholder="Enter Middle Name.." />
                        </div>
                        <div class="form-group col-md-2">
                            <label asp-for="LastName"></label>
                        </div>
                        <div class="form-group col-md-3">
                            <input asp-for="LastName" class="form-control" placeholder="Enter Last Name" />
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </div>
                    </div>
                
                    <div class="form-row">
                        <div class="form-group col-md-2">
                            <label asp-for="NSN"></label>
                        </div>
                        <div class="form-group col-md-3">
                            <input asp-for="NSN" class="form-control" placeholder="Enter NSN number.." />
                        </div>
                        <div class="col-md-2"></div>
                        <div class="form-group col-md-2">
                            <label asp-for="Email"></label>
                        </div>
                        <div class="form-group col-md-3">
                            <input asp-for="Email" class="form-control" />
                        </div>
                    </div>
                 
                    <div class="form-row">
                        <div class="form-group col-md-2">
                            <label asp-for="Designation"></label>
                        </div>
                        <div class="form-group col-md-3">
                            <input asp-for="Designation" class="form-control" placeholder="Enter Role..." />
                        </div>
                        <div class="col-md-2"></div>
                        <div class="form-group col-md-1">
                            <label asp-for="ImageUrl"></label>
                        </div>
                        <div class="form-group col-md-4">
                            <div class="btn btn-primary btn-icon-text">
                                <i class="fas fa-cloud-upload-alt"></i>
                                <input asp-for="ImageUrl" type="file" value="Upload" />
                            </div>
                        </div>
                    </div>
                 

                    <div class="form-group">

                        <button type="submit" class="btn btn-rounded btn-primary float-left"><i class="fas fa-plus-square" style="margin-right:0.7em"></i>Save</button>
                        <a asp-page="_payEmpInfoPartial" class="btn btn-rounded btn-success float-right"><i class="fas fa-caret-square-right" style="margin-right:0.7em"></i>Next</a>
                        <br />
                        <br />
                        <br />

                    </div>
                </form>
   

PayMe.Webapp/Views/Shared/_payEmpInfoPartial.cshtml
<h4>hrllp</h4>